title: Alan Al Yussef
logo: images/mypic_frame.png
description: Doctoral researcher and pedagogical staff 


theme: jekyll-theme-minimal
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"

